ads/dashboard/urls.py
from django.conf.urls import url

from .views import home_view
from .views_create import create_view
from .views_detail import information_view

app_name = 'ads-dashboard'
urlpatterns = [
    url(r'^$', home_view, name='home'), #TODO: testing
    url(r'^create/$', create_view, name='create'), #TODO: testing
    url(r'^(\d+)/$', information_view, name='information'), #TODO: testing
]

api/urls.py
from django.conf.urls import url, include

app_name = 'api'
urlpatterns = [
    # API v5. (reusable apps)
    url(r'^v5/', include('api.v5.urls')),
]

dashboard/urls.py
from axes.decorators import watch_login
from django.conf import settings
from django.conf.urls import url, include
from django.utils.module_loading import import_string

from .views_403 import permission_403_view
from .views_500 import try_500_view
from .views_api_analytic import active_user_view, city_view, session_view, os_view, device_view
from .views_google_report import report_view
from .views_group import group_view
from .views_group_check import group_check_view
from .views_header_group_change import header_group_change_view
from .views_header_provider_change import header_provider_change_view
from .views_import import import_view
from .views_login import login_view
from .views_logout import logout_view
from .views_permission import permission_view
from .views_permission_delete import permission_delete_view

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', import_string(settings.VIEW_DASHBOARD), name='home'),  # TODO: testing
    url(r'^report/$', report_view, name='report'),  # TODO: testing
    # url(r'^$', dashboard_view, name='home'),  # TODO: testing

    url(r'^login/$', watch_login(login_view), name='login'),  # TODO: testing
    url(r'^logout/$', logout_view, name='logout'),  # TODO: testing
    url(r'^403/$', permission_403_view, name='403'),  # TODO: testing
    url(r'^500/$', try_500_view),

    url(r'^header/group/(\d+)/change/$', header_group_change_view, name='header_group_change'),  # TODO: testing
    url(r'^header/provider/(\d+)/change/$', header_provider_change_view, name='header_provider_change'),

    url(r'^import/$', import_view, name='import'),

    url(r'^alert/', include('alert.dashboard.urls')),

    # Account Management
    url(r'^learner/', include('account.dashboard.urls')),  # TODO: testing
    url(r'^department/', include('department.dashboard.urls')),  # TODO: testing
    url(r'^provider/', include('provider.dashboard.urls')),

    url(r'^permission/$', permission_view, name='permission'),  # TODO: testing
    url(r'^permission/(\d+)/delete/(\d+)/$', permission_delete_view, name='permission_delete'),  # TODO: testing

    url(r'^role/$', group_view, name='group'),  # TODO: testing
    url(r'^role/check/$', group_check_view, name='group_check'),  # TODO: testing

    url(r'^level/', include('level.dashboard.urls')),  # TODO: testing

    # Login Report
    url(r'^active/', include('active.dashboard.urls')),

    # Content Management
    url(r'^featured/', include('featured.dashboard.urls')),
    url(r'^category/', include('category.dashboard.urls')),

    # url(r'^featured/', include('featured.dashboard.urls')), #TODO: testing
    url(r'^instructor/', include('tutor.dashboard.urls')),  # TODO: testing
    url(r'^term/', include('term.dashboard.urls')),  # TODO: testing

    # Learning Management
    url(r'^course/', include('course.dashboard.urls')),
    url(r'^question/', include('question.dashboard.urls')),  # TODO: testing
    url(r'^program/', include('program.dashboard.urls')),  # TODO: testing
    url(r'^to-do/', include('task.dashboard.urls')),  # TODO: testing
    url(r'^onboard/', include('program.dashboard.onboard.urls')),  # TODO: testing
    url(r'^lesson/', include('lesson.dashboard.urls')),  # TODO: testing
    url(r'^live/', include('live.dashboard.urls')),  # TODO: testing

    # Assignment Management
    url(r'^assignment/', include('assignment.dashboard.urls')),  # TODO: testing
    url(r'^assignment-auto/', include('assignment_auto.dashboard.urls')),  # TODO: testing
    url(r'^order/', include('order.dashboard.urls')),  # TODO: testing
    url(r'^notification/', include('notification.dashboard.urls')),  # TODO: testing
    url(r'^inbox/', include('inbox.dashboard.urls')),  # TODO: testing

    # Progress & Report
    url(r'^progress/', include('progress.dashboard.urls')),  # TODO: testing

    # Log
    url(r'^log/', include('log.dashboard.urls')),

    # Other
    url(r'^coin/', include('coin.dashboard.urls')),  # TODO: testing
    url(r'^access/', include('access.dashboard.urls')),  # TODO: testing
    url(r'^dependency/', include('dependency.dashboard.urls')),  # TODO: testing
    url(r'^ads/', include('ads.dashboard.urls')),  # TODO: testing

    # JSON
    url(r'^api/active-user/$', active_user_view, name='api_active_user'),  # TODO: testing
    url(r'^api/country/$', city_view, name='api_country'),  # TODO: testing
    url(r'^api/session/$', session_view, name='api_session'),  # TODO: testing
    url(r'^api/os/$', os_view, name='api_os'),  # TODO: testing
    url(r'^api/device/$', device_view, name='api_device'),  # TODO: testing
]

if settings.IS_SUB_PROVIDER:
    from .views_header_sub_provider_change import header_sub_provider_change_view

    urlpatterns += [
        url(r'^header/sub-provider/(\d+)/change/$', header_sub_provider_change_view, name='header_sub_provider_change'),
        # TODO: testing
        url(r'^sub-provider/', include('subprovider.dashboard.urls')),  # TODO: testing
    ]

ondemand/urls.py
from axes.decorators import watch_login
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view

from account.urls import urlpatterns_profile
from account.views_forgot_password import forgot_password_view, save_password_view
from account.views_login import login_view
from account.views_reset_password import reset_password_view
from account.views_signup import signup_view
from ais.views import home_view
from app.api import views as view_apple
from course.views_search import search_view as course_search_view
from pool.rest.views import PoolViesSet
from saml.views import acs
from .views_flatpage import flatpage_view

router = DefaultRouter()
router.register(r'pool', PoolViesSet)

urlpatterns = [
    url(r'^$', home_view, name='home'),

    url(r'^login/$', watch_login(login_view), name='login'),
    url(r'^signup/$', signup_view, name='signup'),
    url(r'^forgot/password/$', forgot_password_view, name='forgot_password'),
    url(r'^forgot/password/save/$', save_password_view, name='forgot_password_save'),
    url(r'^resetpassword/$', reset_password_view, name='reset_password'),
    # url(r'^about/$', about_view, name='about'),
    # url(r'^contact/$', contact_view, name='contact'),
    url(r'^search/$', course_search_view, name='search'),
    url(r'^apple-app-site-association', view_apple.views_apple, name='apple'),
    url(r'^api/', include('api.urls')),
    url(r'^instructor/', include('tutor.urls')),
    url(r'^account/oauth/$', acs),  # Production
    url(r'^saml2/acs/', acs),  # Staging
    url(r'^saml/', include('saml.urls')),  # LOGIN_URL
    url(r'^account/', include('account.urls')),
    url(r'^profile/', include(urlpatterns_profile)),
    url(r'^rating/', include('rating.urls')),
    url(r'^manual/', include('manual.urls')),
    url(r'^discussion/', include('discussion.urls')),

    url(r'^category/', include('category.urls')),

    url(r'^course/', include('course.urls')),
    url(r'^question/', include('question.urls')),
    url(r'^program/', include('program.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^lesson/', include('lesson.urls')),

    url(r'^console/', include('console.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^provider/', include('provider.urls')),

    url(r'^notification/', include('notification.urls')),
    url(r'^mailer/', include('mailer.urls')),
    url(r'^inbox/', include('inbox.urls')),

    url(r'^rest/docs', get_swagger_view(title='Conicle API Docs.')),
    url(r'^rest/', include(router.urls)),

    url(r'^django-admin/login/', watch_login(admin.site.login)),
    url(r'^django-admin/django-rq/', include('django_rq.urls')),
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^about/$', flatpage_view, name="about"),
    url(r'^contact/$', flatpage_view, name="contact"),
    url(r'^term/$', flatpage_view, name="term"),
]

if settings.DEBUG:
    from django.views.static import serve

    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    ]
    try:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls))
        ]
    except:
        pass

featured/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Banner(models.Model):
    # Use Permission Only

    class Meta:
        default_permissions = ('view', 'add', 'change', 'delete')


class Announcement(models.Model):
    # Use Permission Only

    class Meta:
        default_permissions = ('view', 'add', 'change')

        
class Highlight(models.Model):
    code = models.CharField(max_length=32, db_index=True, blank=True, null=True)
    target = models.CharField(max_length=32, db_index=True, blank=True, null=True)

    content = models.BigIntegerField(default=0)

    title = models.CharField(max_length=16, blank=True)
    desc = models.TextField(blank=True)
    url = models.CharField(max_length=256, blank=True)
    image = models.ImageField(upload_to='featured/highlight/image/')
    sort = models.IntegerField(default=0, db_index=True)
    is_display = models.BooleanField(default=True, db_index=True)

    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    timeupdate = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['sort']
        
    @staticmethod
    def pull(id):
        # TODO: Cached
        return Highlight.objects.filter(id=id).first()

    @staticmethod
    def pull_list(code):
        # TODO: Cached
        return Highlight.objects.filter(code=code, is_display=True).order_by('sort')

    def get_target_url(self):

        if self.target == 'course':
            return '%s%s' % (settings.SITE_URL, reverse('course:detail', args=(self.content,)))
        elif self.target == 'question':
            return '%s%s' % (settings.SITE_URL, reverse('question:detail', args=(self.content,)))
        elif self.target == 'program':
            return '%s%s' % (settings.SITE_URL, reverse('program:detail', args=(self.content,)))
        elif self.target == 'task':
            return '%s%s' % (settings.SITE_URL, reverse('task:detail', args=(self.content,)))
        elif self.target == 'link':
            return self.url if 'http' in self.url else 'http://%s' % self.url
        else:
            return None

    def api_display(self):
        return {
            'id': self.id,
            'code': self.code,
            
            'target': self.target,
            'content': self.content,
            'url': self.url,
            
            'title': self.title,
            'desc': self.desc,
            'image': self.image.url if self.image else None,
            'timeupdate': self.timeupdate.strftime(settings.TIMESTAMP_FORMAT_),
        }


class Featured(models.Model):
    content_type = models.ForeignKey('contenttypes.ContentType')
    content = models.BigIntegerField(db_index=True)

    def __str__(self):
        return str(self.content)

    @staticmethod
    def pull(content_type, content):
        if content_type is None:
            # TODO: Cached
            return Featured.objects.filter(id=content).first()
        else:
            featured = Featured.objects.filter(content_type=content_type, content=content).first()
            if featured is None:
                featured = Featured.objects.create(content_type=content_type, content=content)
            return featured

    @staticmethod
    def pull_item(content_type):
        return Item.objects.filter(content_type=content_type)

    def add_item(self, content_type, content):
        item = self.item_set.filter(content_type=content_type,
                                    content=content).first()
        if item is None:
            item = Item.objects.create(featured=self,
                                       content_type=content_type,
                                       content=content,
                                       sort=Item.objects.filter(featured=self,
                                                                content_type=content_type).count())
        return item


class Item(models.Model):
    featured = models.ForeignKey(Featured, null=True, blank=True)
    content_type = models.ForeignKey('contenttypes.ContentType', related_name='+')
    content = models.BigIntegerField(db_index=True)
    sort = models.IntegerField(default=0, db_index=True)

    class Meta:
        ordering = ['sort']

    def get_content(self):
        from utils.content import get_content
        self.content_object = get_content(self.content_type_id, self.content) #TODO: remove
        return get_content(self.content_type_id, self.content)

    # TODO: Remove (use get_content)
    def get_content_cached(self):
        from utils.content_cached import _get_content_cached
        _get_content_cached(self)

term/dashboard/forms.py
from django import forms

from ..models import Term


class TermContentForm(forms.ModelForm):

    class Meta:
        model = Term
        fields = ['body']

        labels = {
            'term': 'Terms & Conitions',
        }

    def __init__(self, *args, **kwargs):
        super(TermContentForm, self).__init__(*args, **kwargs)

account/dashboard/views.py
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render

from alert.models import Alert
from dashboard.views import config_view
from department.cached import cached_department
from department.models import Department
from level.models import Level
from utils.filter import get_q
from utils.filter import get_q_dashboard
from utils.paginator import paginator
from ..models import Account


def home_view(request):
    if request.user.has_perm('account.view_account',
                             group=request.DASHBOARD_GROUP):
        account_list = Account.objects.prefetch_related(
            'department_member_set',
            'level_member_set'
        ).all().order_by('-date_joined')
        q_department_list = Department.objects.filter(parents__isnull=True)
    elif request.user.has_perm('account.view_org_account',
                               group=request.DASHBOARD_GROUP):
        q_department_list = Department.objects.filter(parents__isnull=True)
        if settings.IS_ORGANIZATION:
            account_list = Account.objects.prefetch_related(
                'department_member_set', 'level_member_set'
            ).filter(org_child_set__account=request.user) \
            .distinct() \
            .order_by('is_active', '-date_joined')
        else:
            return config_view(request)
    else:
        raise PermissionDenied

    q_department = get_q_dashboard(request, 'department', 'int')
    if q_department != -1:
        department = cached_department(q_department)
        if department is not None:
            filter_department_list = department.get_all_child()
            account_list = account_list.filter(department_member_set__department__in=filter_department_list)
    q_level = get_q(request, 'q_level')
    if q_level != -1:
        account_list = account_list.filter(level_member_set__level_id=q_level)

    q_name = " ".join(get_q_dashboard(request, 'name', 'str').split())
    if q_name != -1 and len(q_name) > 0:
        account_list = account_list.filter(
            Q(email__icontains=q_name) |
            Q(first_name__icontains=q_name) |
            Q(last_name__icontains=q_name)
        )

    if settings.IS_LIMIT_ACTIVE:
        account_list = account_list.order_by('last_deactivate', '-is_active', 'email')
    else:
        account_list = account_list.order_by('email')

    if settings.ACCOUNT__HIDE_INACTIVE:
        account_list = account_list.exclude(is_active=False)
    if settings.ACCOUNT__HIDE_ID_LIST:
        account_list = account_list.exclude(id__in=settings.ACCOUNT__HIDE_ID_LIST)
    account_list = paginator(request, account_list)

    for account in account_list:
        if account.last_deactivate:
            account.last_deactivate = (account.last_deactivate + settings.TIME_ACTIVE).date()

    q_level_list = Level.objects.all()

    BREADCRUMB_LIST = [
        {'is_active': True,
         'title': 'Learner Management'}
    ]

    alert = Alert.pull_inprogress(request.user, settings.CONTENT_TYPE('account', 'account'), -1)
    result = {
        'SIDEBAR': 'account',
        'BREADCRUMB_LIST': BREADCRUMB_LIST,
        'account_list': account_list,
        'q_department_list': q_department_list,
        'q_level_list': q_level_list,
        'q_department': q_department,
        'q_level': q_level,
        'q_name': q_name,
        'active_amount': Account.objects.filter(is_active=True).count(),
        'is_enable': settings.IS_ENABLE_ACCOUNT,
        'is_force_password': settings.IS_FORCE_RESET_PASSWORD,
        'alert': alert
    }

    if settings.IS_LIMIT_ACTIVE:
        result.update(
            {
                'IS_LIMIT_ACTIVE': settings.IS_LIMIT_ACTIVE,
                'limit_active': settings.MAX_USER
            }
        )

    return render(
        request,
        'account/dashboard/home.html',
        result
    )

featured/templates/featured/dashboard/head.html
<div class="card-header ch-alt">
  <h2><strong>Featured Content</strong></h2>
</div>

featured/templates/featured/dashboard/highlight.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load department_tags %}

{% block content %}
{% include "dashboard/breadcrumb.html" %}
<div class="card">
  <div class="card-header ch-alt">
    <h2><strong>Featured Content</strong></h2>
  </div>
  {% include "featured/dashboard/tab.html" %}
  <div class="card-header">
    <h3 class="clear-pad"><strong>Featured Banner Management</strong></h3>
    <ul class="actions">
      {# {% if perms.highlight.add_webbanner %} #}
      <li>
        <a href="{% url 'dashboard:featured:highlight_add' featured.id code %}">
          <i class="zmdi zmdi-plus-circle"></i> Create New
        </a>
      </li>
      {# {% endif %} #}
    </ul>
  </div>
  <div class="card-body card-padding">
    <div class="table-responsive">
      <table class="table table-hover text-center">
        <thead>
          <tr>
            <th>No.</th>
            <th>Title</th>
            <th>Image</th>
            <th>Sort</th>
            <th>Display</th>
            <th>Edit</th>
            {% comment %}
            <th>Url</th>
            {% endcomment %}
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for item in item_list %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.content_object.title }}</td>
            <td>
              {% if item.content_object.image %}
              <img src="{{ item.content_object.image.url }}" />
              {% else %}-{% endif %}
            </td>
            <td>
              {% if not forloop.first %}
              <a href="{% url 'dashboard:featured:highlight_sort' item.featured_id code item.id %}?move=up" class="btn bgm-teal btn-sm waves-effect">
                <i class="zmdi zmdi-triangle-up zmdi-hc-fw"></i>
              </a>
              {% endif %}
              {% if not forloop.last %}
              <a href="{% url 'dashboard:featured:highlight_sort' item.featured_id code item.id %}?move=down" class="btn bgm-teal btn-sm waves-effect">
                <i class="zmdi zmdi-triangle-down zmdi-hc-fw"></i>
              </a>
              {% endif %}
            </td>
            <td>
              <i class="zmdi zmdi-circle material-display {% if item.content_object.is_display %}text-green{% else %}text-red{% endif %}"></i>
            </td>
            <td>
              <a href="{% url 'dashboard:featured:highlight_detail' item.featured_id code item.id %}" class="btn bgm-bluegray btn-sm waves-effect">
                <i class="zmdi zmdi-edit zmdi-hc-fw"></i>
              </a>
            </td>
            {% comment %}
            <td>
              <a href="{{ web_banner.url }}" target="_blank" class="btn bgm-bluegray btn-sm waves-effect">
                <i class="zmdi zmdi-link zmdi-hc-fw"></i>
              </a>
            </td>
            {% endcomment %}
            <td>
              <a href="{% url 'dashboard:featured:highlight_delete' item.featured_id code item.id %}" onclick="return confirm('Are you sure?')" class="btn btn-danger btn-sm waves-effect">
                <i class="zmdi zmdi-delete zmdi-hc-fw"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="99"><div class="no-item">Hero Banners</div></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include "dashboard/paginator.html" with content_list=web_banner_list %}
    </div>
  </div>
</div>
{% endblock %}

featured/templates/featured/dashboard/highlight_add.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block jquery %}
function banner_display(type){
    $('#id_url').parents('.form-group').hide();
    $('#id_content').parents('.form-group').hide();
    if(type == 'link'){
	$('#id_url').parents('.form-group').show();
    }else if(type == 'course' || type == 'question' || type == 'program' || type == 'task'){
	$('#id_content').parents('.form-group').show();
    }
}

$('body').ready(function(){
    var type = $('select#id_target option:selected').text().substr(0,1).toUpperCase() + $('select#id_target option:selected').text().substr(1);
    $('label[for = id_content]').text(type + ' ID');
});

$('body').on('change', 'select#id_target', function(){
    banner_display(this.value);
    var type = $('select#id_target option:selected').text().substr(0,1).toUpperCase() + $('select#id_target option:selected').text().substr(1);
    $('label[for = id_content]').text(type + ' ID');
    $('input#id_content').val(0);
});

banner_display('{{ highlight.target }}');
{% endblock %}

{% block content %}
{% include "dashboard/breadcrumb.html" %}
<div class="card">
  <div class="card-header ch-alt">
    <h2><strong>{{ code|title }}</strong></h2>
  </div>
  <div class="card-header">
    <h3 class="clear-pad"><strong>Edit Informations</strong></h3>
  </div>
  <div class="card-body card-padding">
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
      {{ highlight_form|bootstrap }}
      <input type="hidden" class="image width" value="{{ IMAGE_SIZE.banner.width }}" />
      <input type="hidden" class="image height" value="{{ IMAGE_SIZE.banner.height }}" />
      <div class="form-group text-right">
        <button type="submit" class="btn bgm-bluegray btn-lg waves-effect" name="save-next">Save</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block modal %}
{% include 'main/modal/modal_crop_image_dashboard.html' %}
{% endblock %}

featured/templates/featured/dashboard/home.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block jquery %}
$('.add-content').click(function(){
    var type = $(this).attr('type');
    $.ajax({
	method: "POST",
	url: "{% url 'dashboard:featured:search' featured.id code %}",
	data: {type: type}
    }).done(function(html) {
	$('#modalSearch-body').html(html);
	$('#modalSearch').modal('show');
    });
    return false;
});

$('body').on('click', '#search-submit', function(){
    $.ajax({
	method: "POST",
	url: "{% url 'dashboard:featured:search' featured.id code %}",
	data: $('#form-search').serialize()
    }).done(function(html){
	$('#modalSearch-body').html(html);
    });
    return false;
});

$('body').on('click', '.insert-content', function(){
    var tag = $(this);
    var content_id = $(this).attr('content');
    var type_id = $(this).attr('type')
    $.ajax({
	method: "POST",
	url: "{% url 'dashboard:featured:search_add' featured.id code %}",
	dataType: "json",
	data: { content: content_id, type: type_id }
    }).done(function(result) {
	tag.parent().html(result.html);
    });
});

$('body').on('click', '.search-delete-item', function(){
    var tag = $(this);
    var item_id = $(this).attr('item');
    $.ajax({
        method: "POST",
        url: "{% url 'dashboard:featured:search_delete' featured.id code %}",
	dataType: "json",
        data: { item: item_id }
    }).done(function(result) {
        tag.parent().html(result.html);
    });
    return false;
});

$('body').on('click', '.delete', function(){
    var item_id = $(this).attr('item');
    $.ajax({
        method: "POST",
        url: "{% url 'dashboard:featured:delete' featured.id code %}",
        data: { item: item_id }
    }).done(function(html) {
        $('#item-block').html(html);
    });
    return false;
});

$('#modalSearch').on('hide.bs.modal', function (event) {
    $.ajax({
        method: "GET",
        url: "{% url 'dashboard:featured:delete' featured.id code %}",
    }).done(function(html) {
        $('#item-block').html(html);
    });
});

$('body').on('click', '.sort', function(){
    var item = $(this).attr('item');
    var action = $(this).attr('action');
    $.ajax({
	method: "POST",
	url: "{% url 'dashboard:featured:sort' featured.id code %}",
	data: {item: item,
	       action: action}
    }).done(function(html){
	$('#item-block').html(html);
    });
    return false;
});
{% endblock %}

{% block content %}
{% include "dashboard/breadcrumb.html" %}
<div class="card">
  {% include "featured/dashboard/head.html" %}
  {% include "featured/dashboard/tab.html" %}
  <div class="card-header">
    <h3 class="clear-pad"><strong>Recommended {{ code|title }} Management</strong></h3>
    <ul class="actions">
      {% if perms.provider.change_provider %}
      <li>
        <a href="#" class="add-content">
          <i class="zmdi zmdi-plus-circle"></i> Create New
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
  <div class="card-body card-padding" id="item-block">
    {% include "featured/dashboard/item_block.html" %}
  </div>
</div>
{% endblock %}
{% block modal %}
  <div class="modal fade" id="modalSearch" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body" id="modalSearch-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn bgm-bluegray btn-lg waves-effect" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

featured/templates/featured/dashboard/stand_alone_add.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block jquery %}
function banner_display(type){
    $('#id_url').parents('.form-group').hide();
    $('#id_content').parents('.form-group').hide();
    if(type == 'link'){
	$('#id_url').parents('.form-group').show();
    }else if(type == 'course' || type == 'question' || type == 'program' || type == 'task'){
	$('#id_content').parents('.form-group').show();
    }
}

$('body').on('change', 'select#id_target', function(){
    banner_display(this.value);
    var type = $('select#id_target option:selected').text().substr(0,1).toUpperCase() + $('select#id_target option:selected').text().substr(1);
    $('label[for = id_content]').text(type + ' ID');
    $('input#id_content').val(0);
});

banner_display('');
{% endblock %}

{% block content %}
{% include "dashboard/breadcrumb.html" %}
<div class="card">
  <div class="card-header ch-alt">
    <h2><strong>{{ code|title }}</strong></h2>
  </div>
  <div class="card-header">
    <h3 class="clear-pad"><strong>{{ code|capfirst }} Management</strong></h3>
  </div>
  <div class="card-body card-padding">
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
      {{ highlight_form|bootstrap }}
      <input type="hidden" class="image width" value="{{ IMAGE_SIZE.banner.width }}" />
      <input type="hidden" class="image height" value="{{ IMAGE_SIZE.banner.height }}" />
      <div class="form-group text-right">
        <button type="submit" class="btn bgm-bluegray btn-lg waves-effect" name="save-next">Save</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block modal %}
{% include 'main/modal/modal_crop_image_dashboard.html' %}
{% endblock %}