api/urls.py
from django.conf.urls import url, include

app_name = 'api'
urlpatterns = [
    # API v5. (reusable apps)
    url(r'^v5/', include('api.v5.urls')),
]

course/urls.py
from django.conf.urls import url

from .views_buy import buy_view, checkout_view
from .views_detail import detail_view, detail_program_view  # , detail_slug_view
from .views_home import new_home_view
from .views_playlist import playlist_view, playlist_program_view
from .views_scorm import scorm_view
from .views_stamp import stamp_view, stamp_program_view
from .views_video_public import vider_public_view

# from .views_group import group_view, grid_view, by_subject_view
# from .views_item import item_view

app_name = 'course'
urlpatterns = [
    url(r'^$', new_home_view, name='home'),
    url(r'^(\d+)/buy/$', buy_view, name='buy'),
    url(r'^(\d+)/checkout/$', checkout_view, name='checkout'),

    url(r'^(\d+)/$', detail_view, name='detail'),
    url(r'^(\d+)/item/(\d+)/$', detail_view, name='detail'),
    url(r'^(\d+)/playlist/(\d+)/(\d+)/$', playlist_view, name='playlist'),
    url(r'^(\d+)/playlist/(\d+)/(\d+)/stamp/$', stamp_view, name='stamp'),

    # In Program
    url(r'^(\d+)/program/(\d+)/$', detail_program_view, name='detail_program'),
    url(r'^(\d+)/program/(\d+)/item/(\d+)/$', detail_program_view, name='detail_program'),
    url(r'^(\d+)/program/(\d+)/playlist/(\d+)/(\d+)/$', playlist_program_view, name='playlist_program'),
    url(r'^(\d+)/program/(\d+)/playlist/(\d+)/(\d+)/stamp/$', stamp_program_view, name='stamp_program'),

    # # TODO: CHECK
    # url(r'^type/(?P<group_name>[\w-]+)/$', group_view, name='group'),  # TODO: testing
    # url(r'^all/$', grid_view, name='course_grid'),  # TODO: testing
    # url(r'^all/(?P<subject_name>[\w-]+)/$', by_subject_view, name='course_subject'),  # TODO: testing
    # url(r'^item/$', item_view, name='item'),  # TODO: testing

    url(r'^(\d+)/material/(\d+)/public/$', vider_public_view, name='video_public'),  # TODO : remove ?

    # Detail Slug
    # url(r'^(\d+)/(.*)/(\d+)/$', detail_slug_view, name='detail'),
    # url(r'^(\d+)/(.*)/$', detail_slug_view, name='detail'),

    url(r'^scorm/$', scorm_view, name='scorm'),
]

ondemand/urls.py
from axes.decorators import watch_login
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view

from account.urls import urlpatterns_profile
from account.views_forgot_password import forgot_password_view, save_password_view
from account.views_login import login_view
from account.views_reset_password import reset_password_view
from account.views_signup import signup_view
from ais.views import home_view
from app.api import views as view_apple
from course.views_search import search_view as course_search_view
from pool.rest.views import PoolViesSet
from saml.views import acs
from .views_flatpage import flatpage_view

router = DefaultRouter()
router.register(r'pool', PoolViesSet)

urlpatterns = [
    url(r'^$', home_view, name='home'),

    url(r'^login/$', watch_login(login_view), name='login'),
    url(r'^signup/$', signup_view, name='signup'),
    url(r'^forgot/password/$', forgot_password_view, name='forgot_password'),
    url(r'^forgot/password/save/$', save_password_view, name='forgot_password_save'),
    url(r'^resetpassword/$', reset_password_view, name='reset_password'),
    # url(r'^about/$', about_view, name='about'),
    # url(r'^contact/$', contact_view, name='contact'),
    url(r'^search/$', course_search_view, name='search'),
    url(r'^apple-app-site-association', view_apple.views_apple, name='apple'),
    url(r'^api/', include('api.urls')),
    url(r'^instructor/', include('tutor.urls')),
    url(r'^account/oauth/$', acs),  # Production
    url(r'^saml2/acs/', acs),  # Staging
    url(r'^saml/', include('saml.urls')),  # LOGIN_URL
    url(r'^account/', include('account.urls')),
    url(r'^profile/', include(urlpatterns_profile)),
    url(r'^rating/', include('rating.urls')),
    url(r'^manual/', include('manual.urls')),
    url(r'^discussion/', include('discussion.urls')),

    url(r'^category/', include('category.urls')),

    url(r'^course/', include('course.urls')),
    url(r'^question/', include('question.urls')),
    url(r'^program/', include('program.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^lesson/', include('lesson.urls')),

    url(r'^console/', include('console.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^provider/', include('provider.urls')),

    url(r'^notification/', include('notification.urls')),
    url(r'^mailer/', include('mailer.urls')),
    url(r'^inbox/', include('inbox.urls')),

    url(r'^rest/docs', get_swagger_view(title='Conicle API Docs.')),
    url(r'^rest/', include(router.urls)),

    url(r'^django-admin/login/', watch_login(admin.site.login)),
    url(r'^django-admin/django-rq/', include('django_rq.urls')),
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^about/$', flatpage_view, name="about"),
    url(r'^contact/$', flatpage_view, name="contact"),
    url(r'^term/$', flatpage_view, name="term"),
]

if settings.DEBUG:
    from django.views.static import serve

    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    ]
    try:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls))
        ]
    except:
        pass

term/urls.py
from django.conf.urls import url

from .views import view
from .views_accept import accept_view

app_name = 'term'
urlpatterns = [

    # USER
    url(r'^$', view, name='home'),  # TODO: testing

    # JS
    url(r'^(\d+)/accept/$', accept_view, name='accept'),  # TODO: testing
]

alert/models.py
from django.db import models


class Alert(models.Model):
    STATUS_CHOICES = (
        (-4, 'Error'),
        (-3, 'File Error'),
        (-2, 'Result Delete'),
        (-1, 'Fail.'),
        (0, 'Upload'),
        (1, 'Process'),
        (2, 'Success'),
        (3, 'Download'),
    )

    account = models.ForeignKey('account.Account')
    code = models.CharField(max_length=12, db_index=True)
    page = models.ForeignKey('contenttypes.ContentType', null=True, blank=True)
    content = models.BigIntegerField(default=-1, db_index=True)
    json_kwargs = models.TextField(blank=True)
    json_result = models.TextField(blank=True)

    file_input = models.CharField(max_length=255, blank=True)
    filename_input = models.CharField(max_length=255, blank=True)

    filename = models.CharField(max_length=255, blank=True, db_index=True)
    file_output = models.CharField(max_length=255, blank=True)
    result = models.TextField(blank=True)

    status = models.IntegerField(choices=STATUS_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-timestamp']

    @staticmethod
    def pull_upload(account, code, page, content, filename):
        from django.utils import timezone
        import uuid
        alert = Alert.objects.filter(
            account=account,
            code=code,
            page=page,
            content=content,
            filename=filename,
            status=0
        ).first()
        if alert is None:
            now = timezone.now()
            uuid = '%s-%s-%s' % (now.year, now.month, uuid.uuid4())
            alert = Alert.objects.create(
                account=account,
                code=code,
                page=page,
                content=content,
                file_input=uuid,
                filename=filename,
                status=0
            )
        return alert

    @staticmethod
    def pull_inprogress(account, content_type, content):
        from django.utils import timezone
        import datetime

        alert = Alert.objects.filter(
            account=account,
            page=content_type,
            status__in=[-1, 1, 2]
        ).first()
        if alert is not None and timezone.now() - alert.timestamp > datetime.timedelta(minutes=5):
            Alert.objects.filter(
                account=account,
                page=content_type,
                status__in=[1, 2]
            ).update(status=-1)
            alert = None
        return alert

    def get_upload_path(self):
        from django.conf import settings
        import os

        path = os.path.join(settings.BASE_DIR, 'alert', 'upload', self.file_input)
        if not os.path.isdir(path):
            os.makedirs(path)
        return path

    def get_export_path(self):
        from django.conf import settings
        import os

        path = os.path.join(settings.BASE_DIR, 'alert', 'export')
        if not os.path.isdir(path):
            os.makedirs(path)
        return path

    def get_user_filename(self):
        from django.conf import settings
        from django.utils import timezone

        def _perfix():
            if self.status == -3:
                return 'FILE_ERROR_LOG'
            elif self.status == -4:
                return 'ERROR_LOG'
            else:
                return 'LOG'

        current_tz = timezone.get_current_timezone()
        local = current_tz.normalize(self.timestamp.astimezone(current_tz))

        if self.page_id == settings.CONTENT_TYPE('progress', 'account').id:
            filename = 'LearnerProgress_'
        elif self.page_id == settings.CONTENT_TYPE('course', 'course').id:
            filename = 'CourseProgress_'
        elif self.page_id == settings.CONTENT_TYPE('question', 'activity').id:
            filename = 'TestProgress_'
        elif self.page_id == settings.CONTENT_TYPE('question', 'question').id:
            filename = 'TestDetailProgress_'
        elif self.page_id == settings.CONTENT_TYPE('program', 'program').id:
            filename = 'ProgramProgress_'
        elif self.page_id == settings.CONTENT_TYPE('program', 'onboard').id:
            filename = 'OnboardProgress_'
        elif self.code == 'department':
            filename = '%s_[%s]_%s.log' % (
                _perfix(),
                self.filename_input,
                local.strftime("%Y%m%d_%H%M%S")
            )
            return filename
        elif self.code == 'om':
            filename = '%s_[%s]_%s.log' % (
                _perfix(),
                self.filename_input,
                local.strftime("%Y%m%d_%H%M%S")
            )
            return filename
        else:
            filename = ''

        filename += local.strftime("%Y-%m-%d--%H-%M")
        return '%s.xls' % filename

    def get_json_result(self):
        _json_result = getattr(self, '_json_result', None)
        if _json_result:
            return _json_result
        else:
            import json
            try:
                _json_result = json.loads(self.json_result)
            except:
                _json_result = {
                    'error': 0,
                    'warning': 0
                }
            setattr(self, '_json_result', _json_result)
            return _json_result

access/dashboard/forms.py
from django import forms
from django.forms import CharField, PasswordInput

from ..models import Account


class AccountForm(forms.ModelForm):

    password = CharField(widget=PasswordInput())

    class Meta:
        model = Account
        fields = ['email', 'password', 'first_name', 'last_name', 'image']
        labels = {
            'email': 'Email',
            'password': 'Password',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'image': 'Profile Image',
        }

        """
        help_texts = {
            'name': '(60)',
            'tutor': 'hold Ctrl button to multiple select',
            'overview': '(400)'
        }
        """

    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'type': 'file'})

account/dashboard/forms.py
from django import forms
from django.forms import CharField, PasswordInput

from ..models import Account

import datetime
from django.conf import settings

class AccountForm(forms.ModelForm):

    password = CharField(widget=PasswordInput())

    class Meta:
        model = Account
        fields = ['email', 'password', 'first_name', 'last_name', 'image']
        labels = {
            'email': 'Email',
            'password': 'Password',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'image': 'Profile Image',
        }

        help_texts = {
            'image': 'Image size 400 x 400 pixel, limit at 100 kb.'
        }

    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'type': 'file'})


class AccountEditForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ['email', 'first_name', 'last_name', 'image', 'gender', 'is_active', 'is_force_reset_password', 'is_enable']
        labels = {
            'email': 'Email',
            'password': 'Password',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'image': 'Profile Image',
        }

        help_texts = {
            'image': 'Image size 400 x 400 pixel, limit at 100 kb.'
        }

    def __init__(self, *args, **kwargs):
        super(AccountEditForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'type': 'file'})
        # Todo limit user
        if settings.IS_LIMIT_ACTIVE:
            if ((self.instance.last_deactivate and datetime.datetime.now().date() < (
                self.instance.last_deactivate + settings.TIME_ACTIVE).date()) \
                        or (Account.objects.filter(is_active=True).count() >= settings.MAX_USER)) \
                    and not self.instance.is_active:
                self.fields['is_active'].widget.attrs.update({'disabled': 'true'})

ads/dashboard/forms.py
# -*- coding: utf-8 -*-
from django import forms

from ..models import Ads


class AdsForm(forms.ModelForm):

    class Meta:
        model = Ads
        fields = ['name', 'image', 'link', 'is_display']

    def __init__(self, *args, **kwargs):
        super(AdsForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'type': 'file'})

assignment_auto/dashboard/forms.py
from django import forms

from assignment_auto.models import AssignmentAuto


class InformationForm(forms.ModelForm):
    content = forms.ChoiceField()

    class Meta:
        model = AssignmentAuto
        fields = ['content_type', 'content', 'hire_start', 'hire_end', 'condition', 'execution_date', 'is_active']
        labels = {

            'condition': 'Condition <br> เงื่อนไข',
            'hire_start': 'Hire Date Start </br> เริ่มจาก',
            'hire_end': 'Hire Date End </br> สิ้นสุด',
            'execution_date': 'Day  Assign </br> ทำงานทุกวันที่',
            'is_active': 'Active </br> ทำงาน',
        }
        help_texts = {
            'execution_date': 'Limit at 31 day. and minimum current day'

        }

    def __init__(self, *args, **kwargs):
        super(InformationForm, self).__init__(*args, **kwargs)
        from django.conf import settings
        from program.models import Program
        CHOICES = list()

        for program in Program.objects.filter(type=2):
            CHOICES.append((program.id, program.name))
        self.fields['content_type'].widget = forms.HiddenInput(attrs={'value': settings.CONTENT_TYPE('program', 'onboard').id})
        self.fields['content'].choices = CHOICES

        self.fields['hire_start'].widget.attrs.update({'max': 31, 'min': 1})
        self.fields['hire_end'].widget.attrs.update({'max': 31, 'min': 1})
        self.fields['execution_date'].widget.attrs.update({'max': 31, 'min': 1})

category/dashboard/forms.py
from django import forms
from django.conf import settings
from ..models import Category


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name', 'image', 'image_featured', 'image_cover', 'is_display']

        labels = {
            'tutor': 'Instructor',
            'is_display': 'Display',
        }

        help_texts = {
            'name': 'Limit at 120 characters',
            'image': settings.HELP_TEXT_IMAGE('category'),
            'image_featured': settings.HELP_TEXT_IMAGE('featured'),
            'image_cover': settings.HELP_TEXT_IMAGE('cover'),
        }

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'type': 'file'})
        self.fields['image_cover'].widget.attrs.update({'type': 'file'})

lesson/dashboard/forms.py
# -*- coding: utf-8 -*-
from django import forms

from ..models import Lesson


class LessonForm(forms.ModelForm):

    class Meta:
        model = Lesson
        fields = ['name', 'image', 'image_cover', 'tutor', 'category', 'status']

        labels = {
            'tutor': 'Publisher',
        }

        help_texts = {
            'name': 'Limit at 60 characters',
            'image': 'Limit file size at 500 kb.',
            'image_cover': 'Limit file size at 500 kb.'
        }

    def __init__(self, *args, **kwargs):
        super(LessonForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'type': 'file'})

course/templates/course/dashboard/access.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% block content %}
<!--course/dashboard/access.html-->
{% include "dashboard/breadcrumb.html" %}
<div class="card">
    {% include "course/dashboard/course_name_head.html" %}
    {% include "course/dashboard/tab.html" %}
    <div class="card-header">
        <h3 class="clear-pad"><strong>Accessibility</strong></h3>
    </div>
    <div class="card-body card-padding">
        <form class="form-horizontal thai" role="form" action="" method="post">{% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">Accessibility Class</label>
                <div class="col-sm-10">
                    <div class="fg-line">
                        <div class="select">
                            <select class=" form-control" name="level_id">
                                <option value="-1">---------</option>
                                {% for level in level_list %}
                                <option value="{{ level.id }}" {% if level.id == content_permission.level.id %}selected{% endif %}>{{ level.name|capfirst }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group text-right">
                <div class="col-sm-offset-2 col-sm-10">
                    {% if perms.course.change_course %}
                    <button type="submit" class="btn bgm-bluegray btn-lg waves-effect" name="save-next">Save</button>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

course/templates/course/dashboard/alert.html
{% if is_progress_update %}
<div class="alert alert-warning" role="alert">
  <strong class="text-black">
    Warning! มีการแก้ไขเนื้อหาที่อยู่ใน Library ของผู้ใช้ กรุณา
    <a href="{% url 'dashboard:course:update' course.id %}">อัพเดต Progress</a>
    ไปที่ผู้ใช้ (เมื่อแก้้ไขเรียบร้อยแล้ว)
  </strong>
</div>
{% endif %}

{% for upload in upload_list %}
<div class="alert alert-info" role="alert"><b>Upload!</b> {{ upload.material.name }} ({{ upload.get_status_display }})</div>
{% endfor %}

course/templates/course/dashboard/course_name_head.html
<div class="card-header ch-alt">
    <h2><strong>Course :</strong> {{ course.name }}</h2>
</div>

course/templates/course/dashboard/create.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% block content %}
<!--course/dashboard/create.html-->
{% include "dashboard/breadcrumb.html" %}
<div class="card">
    <div class="card-header ch-alt">
        <h2><strong>Course Management : Create a new course</strong></h2>
    </div>
    <div class="card-body card-padding">
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ information_form|bootstrap }}
            <input type="hidden" class="image width" value="{{ IMAGE_SIZE.course.width }}" />
            <input type="hidden" class="image height" value="{{ IMAGE_SIZE.course.height }}" />
            <div class="form-group text-right">
                <button type="submit" class="btn bgm-bluegray btn-lg waves-effect" name="save-next">Save & Next Step</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block modal %}
{% include 'main/modal/modal_crop_image_dashboard.html' %}
{% endblock %}

course/templates/course/dashboard/dependency.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block jquery %}
$('.search-content').click(function(){
    var type = $(this).attr('type');
    $.ajax({
	method: "POST",
	url: "{% url 'dashboard:course:dependency_search' course.id %}",
	data: {type: type}
    }).done(function(html) {
	$('#modalSearch-body').html(html);
	$('#modalSearch').modal('show');
    });
    return false;
});

$('body').on('click', '#search-submit', function(){
    $.ajax({
    	method: "POST",
    	url: "{% url 'dashboard:course:dependency_search' course.id %}",
    	data: $('#form-search').serialize()
    }).done(function(html){
	    $('#modalSearch-body').html(html);
    });
    return false;
});

$('body').on('click', '.add-content', function(){
    var tag = $(this);
    var content_type_id = $(this).attr('content_type')
    var content_id = $(this).attr('content');
    var condition = $('#condition-'+content_type_id+'-'+content_id+' option:selected').val();
    $.ajax({
	method: "POST",
	url: "{% url 'dashboard:course:dependency_search_add' course.id %}",
	data: { content_type: content_type_id,
		content: content_id,
		condition: condition}
    }).done(function(html) {
	$('#dependency-block').html(html);
	$('#modalSearch').modal('hide');
    });
});

$('body').on('click', '.search-delete', function(){
    var tag = $(this);
    var parent_id = $(this).attr('parent');
    $.ajax({
        method: "POST",
        url: "{% url 'dashboard:course:dependency_search_delete' course.id %}",
	dataType: "json",
        data: { parent: parent_id }
    }).done(function(result) {
        tag.parent().html(result.html);
    });
    return false;
});

$('body').on('click', '.delete-parent', function(){
    var parent_id = $(this).attr('parent');
    $.ajax({
        method: "POST",
        url: "{% url 'dashboard:course:dependency_delete' course.id %}",
        data: { parent: parent_id }
    }).done(function(html) {
        $('#dependency-block').html(html);
    });
    return false;
});
{% endblock %}

{% block content %}
{% include "dashboard/breadcrumb.html" %}
<div class="card">
    {% include "course/dashboard/course_name_head.html" %}
    {% include "course/dashboard/tab.html" %}
    <div class="error" style="display:none;padding:0 20px;">
      <div class="alert alert-danger" role="alert">
        <strong>Dependency!</strong> <span class="error-msg"></span>
      </div>
    </div>
    <div class="card-header">
        <h3 class="clear-pad"><strong>Dependency</strong></h3>
        <ul class="actions">
            {% if perms.course.change_course %}
            <li class="dropdown">
                <a href="#" data-toggle="dropdown">
                    <i class="zmdi zmdi-plus-circle"></i> Add more items
                </a>
                <ul class="dropdown-menu dm-icon pull-right">
                    {% include "course/dashboard/dependency_menu.html" %}
                </ul>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="card-body card-padding">
        <div class="table-responsive">
            <table class="table table-hover text-center" id="dependency-block">
                {% include "course/dashboard/dependency_block.html" %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block modal %}
{% include "dependency/dashboard/modal/search.html" %}
{% endblock %}

course/templates/course/dashboard/dependency_menu.html
<li>
  <a href="#" class="search-content" type="course">
    <i class="zmdi zmdi-collection-bookmark"></i> Add Courses
  </a>
</li>
<li>
  <a href="#" class="search-content" type="question">
    <i class="zmdi zmdi-assignment-o"></i> Add Tests
  </a>
</li>
<li>
  <a href="#" class="search-content" type="program">
    <i class="zmdi zmdi-storage"></i> Add Programs
  </a>
</li>
<li>
  <a href="#" class="search-content" type="onboard">
    <i class="zmdi zmdi-collection-text"></i> Add Onboardings
  </a>
</li>

course/templates/course/dashboard/level_create.html
{% extends "dashboard/base.html" %}
{% load bootstrap %}
{% block content %}
<!--course/dashboard/level_create.html-->
{% include "dashboard/breadcrumb.html" %}
<div class="card">
    <div class="card-header ch-alt">
        <h2><strong>Content Level Management</strong></h2>
    </div>
    <div class="card-body card-padding">
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ course_level_form|bootstrap_horizontal }}
            <div class="form-group text-right">
                <button type="submit" class="btn bgm-bluegray btn-lg waves-effect">Save</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

course/templates/course/dashboard/progress.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block content %}
{% include "dashboard/breadcrumb.html" %}
<div class="card">
  <div class="card-header ch-alt">
    <h2><strong>Course Progress</strong></h2>
    <ul class="actions">
      <li>
        <a href="?action=update"><i class="zmdi zmdi-refresh zmdi-hc-fw"></i> Refresh</a>
      </li>
    </ul>
  </div>
  <div class="card-body card-padding">
    <div class="container-fluid">
      <h3 class="info-inline">
        {% if course.image %}<img src="{{ course.image.url }}" class="cover" />
        {% else %}<img src="{% static 'images/default-pic-square.png' %}" class="cover" />
        {% endif %}
        <span>{{ course.name }}</span>
      </h3>
      <p class="text-muted">Content Provider : {% if course.provider %}{{ course.provider.name }}{% else %}-{% endif %}</p>
      {# OLD {% include "progress/dashboard/content_count.html" %} #}
      {% include "progress/dashboard/content_count.html" with progress_content=progress_content_sum %}
      {% for progress_content in progress_content_list %}
      <h1>{{ progress_content.location.get_parent.name }}</h1>
      {% include "progress/dashboard/content_count.html" %}
      {% endfor %}
    </div>
    <hr />
    <div class="table-responsive">
      <table class="table table-hover text-center">
        <thead>
          <tr>
            <th>Photo</th>
            <th>Learner</th>
	    <th>Location</th>
            {# <th>Department</th> #}
            {# <th>Direct Manager</th> #}
            <th>Added By</th>
            <th>Last Active</th>
            <th>Due Date</th>
            <th>Status</th>
            <th>Progress</th>
            <th>Days Left (%)</th>
            {# <th>Details</th> #}
            {# <th>Clean</th> #}
          </tr>
        </thead>
        <tbody>
          {% for progress in progress_list %}
          <tr>
            <td>
              {% if progress.account_cached.image %}<img src="{{ progress.account_cached.image.url }}" class="avatar" />
              {% else %}<img src="{% static 'images/profile_default.jpg' %}" class="avatar" />
              {% endif %}
            </td>
            <td class="text-left">{{ progress.account_cached.first_name }} {{ progress.account_cached.last_name }}</td>
	    <td>{{ progress.location.get_parent.name }}</td>
            {# <td>-</td> #}
            {# <td>-</td> #}
            <td>{{ progress.item_cached.order.get_method_display }}</td>
            <td>{{ progress.timeupdate }}</td>
            <td>{{ progress.item_cached.expired_date }}</td>
            <td>{{ progress.get_status_display }}</td>
            <td>{{ progress.content_complete }} / {{ progress.content_count }}</td>
            <td>{{ progress.item_cached.expired_day }}</td>
            {% comment %}
            <td>
              <a href="{% url 'dashboard:progress:detail' account.id %}" class="btn bgm-bluegray btn-sm waves-effect">
                <i class="zmdi zmdi-edit"></i>
              </a>
            </td>
            <td>
              <a href="{% url 'dashboard:progress:onboard_account_clean' course.id progress.account_cached.id progress.item_cached.id %}" class="btn btn-danger btn-sm waves-effect">
                <i class="zmdi zmdi-delete"></i>
              </a>
            </td>
            {% endcomment %}
          </tr>
      	  {% empty %}
          <tr>
            <td colspan="99"><div class="no-item">No progresses.</div></td>
          </tr>
      	  {% endfor %}
        </tbody>
      </table>
      {% include "dashboard/paginator.html" with content_list=progress_list %}
    </div>
  </div>
</div>
{% endblock %}