account/urls.py
from axes.decorators import watch_login
from django.conf import settings
from django.conf.urls import url

from . import views_account, views_facebook, views_address
from . import views_edit
from . import views_info
from .views_change_password import change_password_view
from .views_library import library_view
from .views_live import live_view
from .views_profile import profile_view
from .views_program import program_view
from .views_question import question_view

app_name = 'account'
urlpatterns = [
    url(r'^auth/$', views_account.account_auth),  # js # TODO: testing
    url(r'^logout/$', views_account.logout_view, name='logout'),  # TODO: testing
    url(r'^fblogin/$', views_facebook.account_fblogin),  # js # TODO: testing
    url(r'^fbconnect/$', views_facebook.verify_facebook),  # js # TODO: testing
    url(r'^address/$', views_address.account_address_view),  # js # TODO: testing
    url(r'^image/upload/$', views_edit.upload_view, name='image_upload'),  # js #TODO: testing
]

if settings.PROJECT == 'unilever':
    from unilever.views_login import login_view
    from unilever.views_push import push_view  # Not Encrypt
    from unilever.views_request import request_view  # Encrypt
    urlpatterns += [
        url(r'^login/$', login_view),  # js # TODO: testing
        url(r'^push/$', push_view),  # TODO: testing
        url(r'^request/$', request_view),  # TODO: testing
    ]
elif settings.PROJECT == 'ais':
    from ais.views_login import login_view
    urlpatterns += [
        url(r'^login/$', login_view),  # js # TODO: testing
    ]
else:
    urlpatterns += [
        url(r'^login/$', watch_login(views_account.account_login)),  # js # TODO: testing
    ]

urlpatterns_profile = [
    url(r'^$', profile_view, name='profile'),
    url(r'^info/$', views_info.view, name='profile_info'),
    url(r'^library/$', library_view, name='profile_library'),
    url(r'^program/$', program_view, name='profile_program'),
    url(r'^question/$', question_view, name='profile_question'),
    url(r'^live/$', live_view, name='profile_live'),

    url(r'^password/change/$', change_password_view, name='change_password'),

    url(r'^edit/$', views_edit.edit_view, name='profile_edit'),
    url(r'^edit/action/$', views_edit.action_view, name='profile_edit_action'),
]

api/urls.py
from django.conf.urls import url, include

app_name = 'api'
urlpatterns = [
    # API v5. (reusable apps)
    url(r'^v5/', include('api.v5.urls')),
]

course/urls.py
from django.conf.urls import url

from .views_buy import buy_view, checkout_view
from .views_detail import detail_view, detail_program_view  # , detail_slug_view
from .views_home import new_home_view
from .views_playlist import playlist_view, playlist_program_view
from .views_scorm import scorm_view
from .views_stamp import stamp_view, stamp_program_view
from .views_video_public import vider_public_view

# from .views_group import group_view, grid_view, by_subject_view
# from .views_item import item_view

app_name = 'course'
urlpatterns = [
    url(r'^$', new_home_view, name='home'),
    url(r'^(\d+)/buy/$', buy_view, name='buy'),
    url(r'^(\d+)/checkout/$', checkout_view, name='checkout'),

    url(r'^(\d+)/$', detail_view, name='detail'),
    url(r'^(\d+)/item/(\d+)/$', detail_view, name='detail'),
    url(r'^(\d+)/playlist/(\d+)/(\d+)/$', playlist_view, name='playlist'),
    url(r'^(\d+)/playlist/(\d+)/(\d+)/stamp/$', stamp_view, name='stamp'),

    # In Program
    url(r'^(\d+)/program/(\d+)/$', detail_program_view, name='detail_program'),
    url(r'^(\d+)/program/(\d+)/item/(\d+)/$', detail_program_view, name='detail_program'),
    url(r'^(\d+)/program/(\d+)/playlist/(\d+)/(\d+)/$', playlist_program_view, name='playlist_program'),
    url(r'^(\d+)/program/(\d+)/playlist/(\d+)/(\d+)/stamp/$', stamp_program_view, name='stamp_program'),

    # # TODO: CHECK
    # url(r'^type/(?P<group_name>[\w-]+)/$', group_view, name='group'),  # TODO: testing
    # url(r'^all/$', grid_view, name='course_grid'),  # TODO: testing
    # url(r'^all/(?P<subject_name>[\w-]+)/$', by_subject_view, name='course_subject'),  # TODO: testing
    # url(r'^item/$', item_view, name='item'),  # TODO: testing

    url(r'^(\d+)/material/(\d+)/public/$', vider_public_view, name='video_public'),  # TODO : remove ?

    # Detail Slug
    # url(r'^(\d+)/(.*)/(\d+)/$', detail_slug_view, name='detail'),
    # url(r'^(\d+)/(.*)/$', detail_slug_view, name='detail'),

    url(r'^scorm/$', scorm_view, name='scorm'),
]

inbox/urls.py
from django.conf.urls import url

from .views import inbox_view, inbox_item_view, inbox_popup_item_view
from .views_detail import detail_view
from .views_read import read_view

# from .views_inbox import inbox_view, inbox_popup_view
# from .views_create import create_view
# from .views_notification import notification_view

app_name = 'inbox'
urlpatterns = [
    url(r'^$', inbox_view, name='home'),
    url(r'^(\d+)/$', detail_view, name='detail'),

    url(r'^item/$', inbox_item_view, name='item'),
    url(r'^popup/item/$', inbox_popup_item_view),
    url(r'^read/$', read_view, name='read'),
    # url(r'^notification/$', notification_view, name='notification'),
    # url(r'^notification/popup/$', notification_view, name='notification_popup'),
    # url(r'^create/$', create_view, name='create'),
]

ondemand/urls.py
from axes.decorators import watch_login
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view

from account.urls import urlpatterns_profile
from account.views_forgot_password import forgot_password_view, save_password_view
from account.views_login import login_view
from account.views_reset_password import reset_password_view
from account.views_signup import signup_view
from ais.views import home_view
from app.api import views as view_apple
from course.views_search import search_view as course_search_view
from pool.rest.views import PoolViesSet
from saml.views import acs
from .views_flatpage import flatpage_view

router = DefaultRouter()
router.register(r'pool', PoolViesSet)

urlpatterns = [
    url(r'^$', home_view, name='home'),

    url(r'^login/$', watch_login(login_view), name='login'),
    url(r'^signup/$', signup_view, name='signup'),
    url(r'^forgot/password/$', forgot_password_view, name='forgot_password'),
    url(r'^forgot/password/save/$', save_password_view, name='forgot_password_save'),
    url(r'^resetpassword/$', reset_password_view, name='reset_password'),
    # url(r'^about/$', about_view, name='about'),
    # url(r'^contact/$', contact_view, name='contact'),
    url(r'^search/$', course_search_view, name='search'),
    url(r'^apple-app-site-association', view_apple.views_apple, name='apple'),
    url(r'^api/', include('api.urls')),
    url(r'^instructor/', include('tutor.urls')),
    url(r'^account/oauth/$', acs),  # Production
    url(r'^saml2/acs/', acs),  # Staging
    url(r'^saml/', include('saml.urls')),  # LOGIN_URL
    url(r'^account/', include('account.urls')),
    url(r'^profile/', include(urlpatterns_profile)),
    url(r'^rating/', include('rating.urls')),
    url(r'^manual/', include('manual.urls')),
    url(r'^discussion/', include('discussion.urls')),

    url(r'^category/', include('category.urls')),

    url(r'^course/', include('course.urls')),
    url(r'^question/', include('question.urls')),
    url(r'^program/', include('program.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^lesson/', include('lesson.urls')),

    url(r'^console/', include('console.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^provider/', include('provider.urls')),

    url(r'^notification/', include('notification.urls')),
    url(r'^mailer/', include('mailer.urls')),
    url(r'^inbox/', include('inbox.urls')),

    url(r'^rest/docs', get_swagger_view(title='Conicle API Docs.')),
    url(r'^rest/', include(router.urls)),

    url(r'^django-admin/login/', watch_login(admin.site.login)),
    url(r'^django-admin/django-rq/', include('django_rq.urls')),
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^about/$', flatpage_view, name="about"),
    url(r'^contact/$', flatpage_view, name="contact"),
    url(r'^term/$', flatpage_view, name="term"),
]

if settings.DEBUG:
    from django.views.static import serve

    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    ]
    try:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls))
        ]
    except:
        pass

tutor/urls.py
from django.conf.urls import url

from .views import home_view
from .views_detail import detail_view

app_name = 'tutor'
urlpatterns = [
    url(r'^$', home_view, name='home'),  # TODO: testing
    url(r'^(\d+)/$', detail_view, name='detail'),  # TODO: testing
]

templates/cbsibo/main/browse_menu.html
{% load staticfiles %}
{% if is_provider  %}
<li><a href="{% url 'home' %}"><i class="main-color fa fa-arrow-left"></i> Back to Homepage</a></li>
<li class="text-center">
  <a href="{% url 'provider:detail' provider.id %}" class="browse-menu-logo vertical-middle clear-pad">
    {% if provider.image %}
    <img src="{{ provider.image.url }}" class="full-width" />
    {% else %}
    <img src="{% static 'cbsibo/images/customize/logo-square.png' %}" class="full-width" />
    {% endif %}
    <strong>{{ provider.name }}</strong>
  </a>
</li>
<li {% if ROOT_PAGE == 'provider_detail' %}class="active"{% endif %}><a href="{% url 'provider:detail' provider.id %}"><i class="fa fa-university"></i> {{ provider.name }}</a></li>
<li {% if ROOT_PAGE == 'provider_program' %}class="active"{% endif %}><a href="{% url 'provider:program' provider.id %}"><i class="fa fa-th"></i> Programs</a></li>
<li {% if ROOT_PAGE == 'provider_course' %}class="active"{% endif %} >
  <a href="{% url 'provider:course' provider.id %}"><i class="fa fa-play-circle-o"></i> Courses</a>
  <ul class="unstyle">
    {% for item in course_menu_subject %}
    <li><a href="{% url 'provider:course' provider.id %}?category={{ item.subject.id }}">{{ item.subject.name }}</a></li>
    {% endfor %}
  </ul>
</li>
<li {% if ROOT_PAGE == 'provider_tutor' %}class="active"{% endif %}><a href="{% url 'provider:tutor' provider.id %}"><img src="{% static 'images/icons/menu-black/instructors.png' %}" class="img-menu-icon"/> Instructors</a></li>
<li {% if ROOT_PAGE == 'provider_about' %}class="active"{% endif %}><a href="{% url 'provider:about' provider.id %}"><img src="{% static 'images/icons/menu-black/about.png' %}" class="img-menu-icon"/> About</a></li>
{% else %}
<li class="{% if ROOT_PAGE == 'home' %}active{% endif %} margin-20-0"><a href="{% url 'home' %}"><img src="{% static 'images/icons/menu-black/home.png' %}" class="img-menu-icon"/> Home</a></li>
{% if user.is_authenticated %}
<li class="{% if ROOT_PAGE == 'profile' %}active{% endif %}"><a href="{% url 'profile' %}"><img src="{% static 'images/icons/menu-black/myLibrary.png' %}" class="img-menu-icon"/> My Library</a></li>
{% if IS_ONBOARD_ACTIVE %}
<li class="{% if ROOT_PAGE == 'onboard' %}active{% endif %}"><a href="{% url 'program:onboard' %}"><img src="{% static 'images/icons/menu-black/myOnboard.png' %}" class="img-menu-icon"/> My Onboard</a></li>
{% endif %}
{% comment %}
<li class="{% if ROOT_PAGE == 'admin' %}active{% endif %}"><a href="{% url 'profile_info' %}">My Admin</a></li>
{% endcomment %}
{% endif %}
<li class="{% if ROOT_PAGE == 'program' %}active{% endif %}"><a href="{% url 'program:home' %}"><img src="{% static 'images/icons/menu-black/program.png' %}" class="img-menu-icon"/> All Programs</a></li>
<li class="{% if ROOT_PAGE == 'course' %}active{% endif %}"><a href="{% url 'course:home' %}"><img src="{% static 'images/icons/menu-black/course.png' %}" class="img-menu-icon"/> All Courses</a></li>
<li class="hidden-some-menu relative {% if ROOT_PAGE == 'subject' %}active{% endif %}">
  <a href="{% url 'category:home' %}"><img src="{% static 'images/icons/menu-black/category.png' %}" class="img-menu-icon"/> Categories</a>
  {% if HEADER_COURSE_CATEGORY|length > 0 %}<i class="fa fa-plus btn-show-all"></i>{% endif %}
  <i class="fa fa-minus btn-hide"></i>
  <ul class="unstyle">
    {% for category_item in HEADER_COURSE_CATEGORY %}
    <li {% if ROOT_PAGE == category_item.id %}class="active"{% endif %}><a href="{% url 'category:detail' category_item.id %}" title="{{ category_item.name }}"> {{ category_item.name }}</a></li>
    {% endfor %}
  </ul>
</li>
<!-- <li class="hidden-some-menu relative {% if ROOT_PAGE == 'provider' %}active{% endif %}">
  <a href="{% url 'provider:home' %}"><img src="{% static 'images/icons/menu-black/learningCenter.png' %}" class="img-menu-icon"/> Learning Centers</a>
  {% if HEADER_PROVIDER|length > 0 %}<i class="fa fa-plus btn-show-all"></i>{% endif %}
  <i class="fa fa-minus btn-hide"></i>
  <ul class="unstyle">
    {% for provider in HEADER_PROVIDER %}
    <li><a href="{% url 'provider:detail' provider.id %}" title="{{ provider.name }}">{{ provider.name }}</a></li>
    {% endfor %}
  </ul>
</li> -->
<li class="{% if ROOT_PAGE == 'tutor' %}active{% endif %}"><a href="{% url 'tutor:home' %}"><img src="{% static 'images/icons/menu-black/instructors.png' %}" class="img-menu-icon"/> Instructors</a></li>
<li class="{% if ROOT_PAGE == 'contact' %}active{% endif %}"><a href="{% url 'contact' %}"><img src="{% static 'images/icons/menu-black/mail.png' %}" class="img-menu-icon"/> Contact</a></li>
<li class="{% if ROOT_PAGE == 'about' %}active{% endif %}"><a href="{% url 'about' %}"><img src="{% static 'images/icons/menu-black/about.png' %}" class="img-menu-icon"/> About</a></li>
<li class="{% if ROOT_PAGE == 'term' %}active{% endif %}"><a href="{% url 'term' %}"><img src="{% static 'images/icons/menu-black/term.png' %}" class="img-menu-icon"/> Terms of Service</a></li>
{% if user.is_authenticated %}
<li><a href="{% url 'account:logout' %}"><img src="{% static 'images/icons/menu-black/logout.png' %}" class="img-menu-icon"/> Logout</a></li>
{% else %}
<li><a href="#" data-toggle="modal" data-target="#loginModal"><i class="fa fa-sign-in"></i> Log In</a></li>
{% endif %}
{% endif %}
<script>
  $(function(){
  $('.hidden-some-menu').each(function(){
  /*if($(this).find('ul li').size()<=4){
    $(this).find('.btn-show-all').hide();
    }*/
  });
  });
</script>

templates/cbsibo/main/header.html
{% load staticfiles %}
{% url 'home' as home_url %}
{% if not IS_WEBVIEW %}
<header id="header">
  <ul class="unstyle">
    {% if PARENT_URL %}
    <li class="btn-back">
      <a href="{{ PARENT_URL }}" {% comment %}onclick="history.back()"{% endcomment %}><i class="fa fa-arrow-left"></i></a>
    </li>{% else %}<li class="show-mobile">
      <a href="#" class="open-side-menu text-white"><i class="fa fa-bars"></i></a>
    </li><li id="menu-trigger" class="browse has-sub-menu hide-sm">
      <a href="#">
        {% comment %}
        {% if is_provider and provider.image %}<img src="{{ provider.image.url }}" class="sub-logo" />
        {% else %}Browse{% endif %}
        <i class="fa fa-caret-down"></i>
        {% endcomment %}
        <div class="line-wrap">
          <div class="line top"></div>
          <div class="line center"></div>
          <div class="line bottom"></div>
        </div>
      </a>
      <ul class="unstyle sub-menu">
        {% include "main/browse_menu.html" %}
      </ul>
    </li>{% endif %}
    <li class="logo">
      <a href="{{ home_url }}">
        <img src="{% static logo_path|default:'cbsibo/images/customize/logo-white.png' %}" />
      </a>
    </li>
  </ul>
  <div class="search hide-sm">
    <form action="{% url 'search' %}" method="GET">
      <input type="text" name="q" maxlength="60" placeholder="Search">
    </form>
  </div>
  <ul class="unstyle pull-right">
    {% if not user.is_authenticated %}
    <li class="hide-sm">
      <a href="#" data-toggle="modal" data-target="#loginModal"><i class="icon icon-lock"></i>Login</a>
    </li>
    {% endif %}
    {% if user.is_authenticated %}
    <li id="notificationBell" class="notification-dropdown {% if INBOX_COUNT > 0 %}new-alert{% endif %} has-sub-menu hide-sm">
      <a href="#" style="font-size:24px;"><i class="fa fa-bell"></i></a>
      <ul class="sub-menu dropdown-menu">
        <li class="dropdown-heading text-center">NOTIFICATIONS</li>
        <li class="dropdown-empty"><p class="text-center">You have no notification.</p></li>
        <li class="dropdown-footer"><a href="{% url 'inbox:home' %}">View All</a></li>
      </ul>
    </li>
    <li class="profile has-sub-menu hide-sm">
      <a href="{% url 'profile' %}">
        {% if user.image %}<img src="{{ user.image.url }}" class="avatar" />
        {% else %}<img src="{% static 'images/profile_default.jpg' %}" class="avatar" />
        {% endif %}
      </a>
    </li>
    {% endif %}
    <li class="show-mobile">
      <a href="#" class="btn-open-search text-white"><i class="fa fa-search"></i></a>
    </li>
    <li class="btn-close-search">
      <a href="#" class="font-20"><i class="fa fa-times-circle"></i></a>
    </li>
  </ul>
</header>
<ul class="unstyle left-menu hide-md">
  {% include "main/browse_menu.html" %}
</ul>
{% include "main/header_menu_mobile.html" %}
{% endif %}

templates/cbsibo/main/header_menu_mobile.html
{% load static %}
<nav id="side-menu-wrapper">
  <ul class="unstyle main-side-menu">
    <li class="profile text-center">
      {% if user.is_authenticated %}
      {% if user.image %}
      <img src="{{ user.image.url }}" class="avatar" />
      {% else %}
      <img src="{% static 'images/profile_default.jpg' %}" class="avatar" />
      {% endif %}
      <h5>{{ user.first_name }} {{ user.last_name }}</h5>
      <ul class="unstyle flex text-center">
        <li><a href="{% url 'profile' %}"><i class="fa fa-user"></i><br />My Profile</a></li>
        <li><a href="{% url 'inbox:home' %}"><i class="fa fa-bell"></i>{% if INBOX_COUNT %}<span class="badge">N</span>{% endif %}<br />Notifications</a></li>
      </ul>
      {% else %}
      <img src="{% static 'cbsibo/images/customize/logo-square.png' %}" class="avatar" />
      <h4>Learning Station</h4>
      {% endif %}
    </li>

    {% include "main/browse_menu.html" %}
    <li class="side-menu-footer">
      <p><img src="{% static logo_path|default:'cbsibo/images/customize/logo-square.png' %}" width="150" /></p>
      <p>Copyright <i class="fa fa-copyright"></i> {% now "Y" %} CBS Innovative Business Online.</p>
      <p>All rights reserved.</p>
    </li>
  </ul>
  <i class="fa fa-times font-30 close-side-menu text-white"></i>
</nav>